% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={ProblemSet7},
  pdfauthor={Dilip Nikhil Francies},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{ProblemSet7}
\author{Dilip Nikhil Francies}
\date{2023-10-19}

\begin{document}
\maketitle

\hypertarget{question-2-5-points.-from-the-spring-2017-final.-i-downloaded-data-on-the-number-of-citations-for-a-random-sample-of-1000-journal-articles-published-in-1981.-the-data-is-from-the-isi-citation-indexes.-i-ran-some-analysis-on-the-data-in-r-and-produced-the-following-output}{%
\subsubsection{Question 2: (5 points. From the Spring 2017 final.) I
downloaded data on the number of citations for a random sample of 1000
journal articles published in 1981. (The data is from the ISI Citation
Indexes.) I ran some analysis on the data in R, and produced the
following
output}\label{question-2-5-points.-from-the-spring-2017-final.-i-downloaded-data-on-the-number-of-citations-for-a-random-sample-of-1000-journal-articles-published-in-1981.-the-data-is-from-the-isi-citation-indexes.-i-ran-some-analysis-on-the-data-in-r-and-produced-the-following-output}}

\hypertarget{answer}{%
\subsubsection{Answer :}\label{answer}}

\hypertarget{a-is-the-distribution-of-the-number-of-citations-i-exactly-normal-ii-approximately-normal-or-iii-not-close-to-normal-how-do-you-know}{%
\paragraph{2a: Is the distribution of the number of citations (i)
exactly normal, (ii) approximately normal, or (iii) not close to normal?
How do you
know?}\label{a-is-the-distribution-of-the-number-of-citations-i-exactly-normal-ii-approximately-normal-or-iii-not-close-to-normal-how-do-you-know}}

We know that for a normal distribution, IQR is given by 1.349 * Standard
deviation

Given: variance of the distribution = 565.2476. Lets calculate standard
deviation:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sd }\OtherTok{=} \FunctionTok{sqrt}\NormalTok{(}\FloatTok{565.2476}\NormalTok{)}
\NormalTok{sd}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 23.77494
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{IQR }\OtherTok{=} \FloatTok{1.349} \SpecialCharTok{*}\NormalTok{ sd}
\NormalTok{IQR}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 32.07239
\end{verbatim}

From the given information, we have IQR = Q3- Q1 = 7.25 - 0.00 = 7.25.

Secondly, for a normal distribution, the mean and median is equal or
close to each other. From the given data, we have mean = 9.06, and
median 1.00. As mean is more than median, the distribution would be
positively skewed.

Hence the IQR values, 32.07239 and 7.25 are not even relatively close to
each other, and mean of the distribution is more than the median. Hence
the distribution is not normal.

\hypertarget{question-2b-find-an-approximate-95-confidence-interval-for-the-mean-number-of-citations}{%
\paragraph{Question 2b: Find an approximate 95\% confidence interval for
the mean number of
citations}\label{question-2b-find-an-approximate-95-confidence-interval-for-the-mean-number-of-citations}}

Given : mean = 9.06, variance = 565.2476 Lets calculate standard
deviation and standard error:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mean }\OtherTok{\textless{}{-}} \FloatTok{9.06}
\NormalTok{sd }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FloatTok{565.2476}\NormalTok{)}
\NormalTok{se }\OtherTok{\textless{}{-}}\NormalTok{ sd}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{1000}\NormalTok{)          }\CommentTok{\# n = 1000, given}
\end{Highlighting}
\end{Shaded}

For 95\% confidence interval, alpha = 0.05, alpha/2 = 0.025.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{upperbound }\OtherTok{\textless{}{-}}\NormalTok{ mean }\SpecialCharTok{+} \FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ se}
\NormalTok{lowerbound }\OtherTok{\textless{}{-}}\NormalTok{ mean }\SpecialCharTok{{-}} \FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ se}

\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"The approximate 95\% confidence interval for the mean number of citations is"}\NormalTok{ ,upperbound ,}\StringTok{"and"}\NormalTok{ ,lowerbound))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "The approximate 95% confidence interval for the mean number of citations is 10.5335587463336 and 7.58644125366642"
\end{verbatim}

\hypertarget{c-find-an-approximate-95-confidence-interval-for-the-proportion-of-journal-articles-with-no-citations.}{%
\paragraph{2c: Find an approximate 95\% confidence interval for the
proportion of journal articles with no
citations.}\label{c-find-an-approximate-95-confidence-interval-for-the-proportion-of-journal-articles-with-no-citations.}}

Given: Proportion of articles with no citations = 460 out of 1000
citations. This can be considered as Bernoulli trials where a journal
either has a citation or not. hence, p = 0.46. For a 1000 trials, we can
estimate sample mean xbar to be good estimate of p.~hence, standard
deviation of the sample is give by (sqrt(xbar*(1-xbar)))

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{xbar }\OtherTok{\textless{}{-}} \FloatTok{0.46}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{1000}                                     \CommentTok{\# given}
\NormalTok{sd }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(xbar}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{xbar)) }
\NormalTok{se }\OtherTok{\textless{}{-}}\NormalTok{ sd}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(n)}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"hence, the plug in estimate of standard deviation is"}\NormalTok{ ,sd ,}\StringTok{"and the standard error is"}\NormalTok{ ,se))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "hence, the plug in estimate of standard deviation is 0.498397431775085 and the standard error is 0.0157607106438764"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{upperbound }\OtherTok{\textless{}{-}}\NormalTok{ xbar }\SpecialCharTok{+} \FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ se}
\NormalTok{lowerbound }\OtherTok{\textless{}{-}}\NormalTok{ xbar}\SpecialCharTok{{-}} \FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ se}

\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Therfore, for 95\% confidence interval of journal with no citation is"}\NormalTok{,lowerbound , }\StringTok{"and"}\NormalTok{ ,upperbound))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Therfore, for 95% confidence interval of journal with no citation is 0.429109574767245 and 0.490890425232755"
\end{verbatim}

\hypertarget{question-3}{%
\paragraph{Question 3:}\label{question-3}}

\hypertarget{a-plot-the-distributions-of-the-raw-feeling-thermometer-scores-for-trump-clinton-and-sanders-on-the-same-scale.-whats-wrong-with-the-data}{%
\subparagraph{3a : Plot the distributions of the raw feeling thermometer
scores for Trump, Clinton, and Sanders on the same scale. What's wrong
with the
data?}\label{a-plot-the-distributions-of-the-raw-feeling-thermometer-scores-for-trump-clinton-and-sanders-on-the-same-scale.-whats-wrong-with-the-data}}

\#Lets read the data first:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read.table}\NormalTok{(}\StringTok{"ANES2016.txt"}\NormalTok{,}\AttributeTok{header =} \ConstantTok{TRUE}\NormalTok{)}
\FunctionTok{nrow}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3600
\end{verbatim}

Distribution of the entire data:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'ggplot2' was built under R version 4.2.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Thermometer)) }\SpecialCharTok{+}\FunctionTok{geom\_histogram}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\includegraphics{PS7_files/figure-latex/unnamed-chunk-7-1.pdf}

Distribution of Trump:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{trump }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(data,Candidate }\SpecialCharTok{==} \StringTok{"Trump"}\NormalTok{)}
\FunctionTok{nrow}\NormalTok{(trump)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1200
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(trump, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Thermometer)) }\SpecialCharTok{+}\FunctionTok{geom\_histogram}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\includegraphics{PS7_files/figure-latex/unnamed-chunk-8-1.pdf}

Distribution of Clinton:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{clinton }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(data,Candidate }\SpecialCharTok{==} \StringTok{"Clinton"}\NormalTok{)}
\FunctionTok{ggplot}\NormalTok{(clinton, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Thermometer)) }\SpecialCharTok{+}\FunctionTok{geom\_histogram}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\includegraphics{PS7_files/figure-latex/unnamed-chunk-9-1.pdf}

Distribution of Sanders:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sanders }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(data,Candidate }\SpecialCharTok{==} \StringTok{"Sanders"}\NormalTok{)}
\FunctionTok{ggplot}\NormalTok{(sanders, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Thermometer)) }\SpecialCharTok{+}\FunctionTok{geom\_histogram}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\includegraphics{PS7_files/figure-latex/unnamed-chunk-10-1.pdf}

What's wrong with the data? Answer : One can clearly see that there are
outliers present in the data for all three people. When the majority of
the data lies within 0-125, there are values that go beyond 990.

\hypertarget{b}{%
\paragraph{3b :}\label{b}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{therm100 }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(data,Thermometer }\SpecialCharTok{\textless{}=}\DecValTok{100}\NormalTok{)}

\NormalTok{trump }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(therm100,Candidate }\SpecialCharTok{==} \StringTok{"Trump"}\NormalTok{)}
\NormalTok{meanTrump }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(trump}\SpecialCharTok{$}\NormalTok{Thermometer)}
\NormalTok{sdTrump }\OtherTok{=} \FunctionTok{sd}\NormalTok{(trump}\SpecialCharTok{$}\NormalTok{Thermometer)}

\NormalTok{clinton }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(therm100,Candidate }\SpecialCharTok{==} \StringTok{"Clinton"}\NormalTok{)}
\NormalTok{meanClint }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(clinton}\SpecialCharTok{$}\NormalTok{Thermometer)}
\NormalTok{sdClint }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(clinton}\SpecialCharTok{$}\NormalTok{Thermometer)}

\NormalTok{sanders }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(therm100,Candidate }\SpecialCharTok{==} \StringTok{"Sanders"}\NormalTok{)}
\NormalTok{meanSander }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(sanders}\SpecialCharTok{$}\NormalTok{Thermometer)}
\NormalTok{sdSanders }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(sanders}\SpecialCharTok{$}\NormalTok{Thermometer)}

\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Trump : Standard deviation is"}\NormalTok{,sdTrump,}\StringTok{"and mean is"}\NormalTok{, meanTrump ))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Trump : Standard deviation is 36.5289728313274 and mean is 38.3784461152882"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Clinton : Standard deviation is"}\NormalTok{,sdClint,}\StringTok{"and mean is"}\NormalTok{, meanClint ))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Clinton : Standard deviation is 36.5047045603107 and mean is 42.9941618015012"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Sanders : Standard deviation is"}\NormalTok{,sdSanders,}\StringTok{"and mean is"}\NormalTok{, meanSander ))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Sanders : Standard deviation is 33.3909085154214 and mean is 50.4119127516779"
\end{verbatim}

\hypertarget{question-3c}{%
\paragraph{Question 3c:}\label{question-3c}}

\begin{enumerate}
\def\labelenumi{\roman{enumi}.}
\tightlist
\item
  Trump
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{nrow}\NormalTok{(trump)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1197
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{seTrump }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(trump}\SpecialCharTok{$}\NormalTok{Thermometer)}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{1197}\NormalTok{)}
\NormalTok{upperbound }\OtherTok{\textless{}{-}}\NormalTok{ meanTrump }\SpecialCharTok{+} \FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.995}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ seTrump            }\CommentTok{\#99\% confidence interval}
\NormalTok{lowerbound }\OtherTok{\textless{}{-}}\NormalTok{ meanTrump }\SpecialCharTok{{-}} \FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.995}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ seTrump}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Therfore, for 99\% confidence interval of Trumps mean feeling thermometer of"}\NormalTok{,meanTrump,}\StringTok{" is"}\NormalTok{, upperbound, }\StringTok{"and"}\NormalTok{, lowerbound))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Therfore, for 99% confidence interval of Trumps mean feeling thermometer of 38.3784461152882  is 41.098061346077 and 35.6588308844995"
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\roman{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Clinton
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{nrow}\NormalTok{(clinton)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1199
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{seClint }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(clinton}\SpecialCharTok{$}\NormalTok{Thermometer)}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{1199}\NormalTok{)}
\NormalTok{upperbound }\OtherTok{\textless{}{-}}\NormalTok{ meanClint }\SpecialCharTok{+} \FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.995}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ seClint            }\CommentTok{\#99\% confidence interval}
\NormalTok{lowerbound }\OtherTok{\textless{}{-}}\NormalTok{ meanClint }\SpecialCharTok{{-}} \FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.995}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ seClint}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Therfore, for 99\% confidence interval of Clinton mean feeling thermometer of"}\NormalTok{,meanClint,}\StringTok{" is"}\NormalTok{, upperbound, }\StringTok{"and"}\NormalTok{, lowerbound))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Therfore, for 99% confidence interval of Clinton mean feeling thermometer of 42.9941618015012  is 45.709702562102 and 40.2786210409005"
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\roman{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Sander:
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{nrow}\NormalTok{(sanders)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1192
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{seSanders }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(sanders}\SpecialCharTok{$}\NormalTok{Thermometer)}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{1192}\NormalTok{)}
\NormalTok{upperbound }\OtherTok{\textless{}{-}}\NormalTok{ meanSander }\SpecialCharTok{+} \FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.995}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ seSanders            }\CommentTok{\#99\% confidence interval}
\NormalTok{lowerbound }\OtherTok{\textless{}{-}}\NormalTok{ meanSander }\SpecialCharTok{{-}} \FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.995}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ seSanders}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Therfore, for 99\% confidence interval of Sanders mean feeling thermometer of"}\NormalTok{,meanSander,}\StringTok{" is"}\NormalTok{, upperbound, }\StringTok{"and"}\NormalTok{, lowerbound))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Therfore, for 99% confidence interval of Sanders mean feeling thermometer of 50.4119127516779  is 52.9031046771597 and 47.920720826196"
\end{verbatim}

\hypertarget{question-5in-a-may-2019-gallup-poll1-63-of-a-sample-of-1009-u.s.-adults-supported-same-sex-marriage.}{%
\paragraph{Question 5:In a May 2019 Gallup poll,1 63\% of a sample of
1009 U.S. adults supported same-sex
marriage.}\label{question-5in-a-may-2019-gallup-poll1-63-of-a-sample-of-1009-u.s.-adults-supported-same-sex-marriage.}}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  Treating the data as a simple random sample, find a 95\% confidence
  interval for the percentage of all U.S. adults who support same-sex
  marriage.
\end{enumerate}

Answer: We can consider this as Bernoulli trial where every individual
either supports or does not support same-sex marriage. Hence, p is given
by 0.63 and sample size n = 1009. For a Bernoulli random variable, it is
sage to assume p as the expected value, ie xbar = 0.63.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{xbar }\OtherTok{\textless{}{-}} \FloatTok{0.63}
\NormalTok{sd }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(xbar }\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{xbar))}
\NormalTok{se }\OtherTok{\textless{}{-}}\NormalTok{ sd }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(}\DecValTok{1009}\NormalTok{)}
\NormalTok{se}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.01519937
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{upperbound }\OtherTok{\textless{}{-}}\NormalTok{ xbar }\SpecialCharTok{+} \FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ se}
\NormalTok{lowerbound }\OtherTok{\textless{}{-}}\NormalTok{ xbar }\SpecialCharTok{{-}} \FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ se}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Hence, 95\% confidence interval for the percentage of all US adults who supports same sex marriage is"}\NormalTok{,upperbound,}\StringTok{"and"}\NormalTok{,lowerbound))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Hence, 95% confidence interval for the percentage of all US adults who supports same sex marriage is 0.659790215485221 and 0.600209784514779"
\end{verbatim}

\hypertarget{b-suppose-we-wanted-to-have-a-95-confidence-interval-for-the-percentage-of-all-u.s.-adults-who-support-same-sex-marriage-with-total-length-2-i.e.-0.02.-how-large-a-simple-random-sample-would-we-need}{%
\paragraph{5b) Suppose we wanted to have a 95\% confidence interval for
the percentage of all U.S. adults who support same-sex marriage with
total length 2\% (i.e.~0.02.) How large a simple random sample would we
need?}\label{b-suppose-we-wanted-to-have-a-95-confidence-interval-for-the-percentage-of-all-u.s.-adults-who-support-same-sex-marriage-with-total-length-2-i.e.-0.02.-how-large-a-simple-random-sample-would-we-need}}

Answer: we know that, Length ``L'' is given by (2 * q *sd / sqrt(n))
Which give us:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.975}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.959964
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#plugging in the values for the above equation we get}

\NormalTok{n }\OtherTok{=}\NormalTok{ ((}\DecValTok{2}\SpecialCharTok{*}\FloatTok{1.9599} \SpecialCharTok{*}\NormalTok{ xbar}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{xbar)) }\SpecialCharTok{/}\FloatTok{0.02}\NormalTok{)}\SpecialCharTok{\^{}}\DecValTok{2}
\NormalTok{n }\OtherTok{=} \DecValTok{38416}\SpecialCharTok{*}\NormalTok{(xbar}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{xbar))}

\CommentTok{\#Option 1:}
  \CommentTok{\#Lets consider xbar = 0.63}
\NormalTok{n1 }\OtherTok{=} \DecValTok{38416}\SpecialCharTok{*}\NormalTok{(}\FloatTok{0.63}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\FloatTok{{-}0.63}\NormalTok{))}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"When xbar is 0.63, the sample size required is"}\NormalTok{, n1))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "When xbar is 0.63, the sample size required is 8954.7696"
\end{verbatim}

\hypertarget{question-4.-mt.-wrightson-the-fifth-highest-summit-in-arizona-and-the-highest-in-pima-county-has-a-reputed-elevation-of-9453-feet.-to-amuse-its-members-the-southern-arizona-hiking-club-sahc-decides-to-construct-its-own-confidence-interval-for-ux3bc-the-true-elevation-of-mt.-wrightsons-summit.-sahc-acquires-an-altimeter-whose-measurements-will-have-an-expected-value-of-ux3bc-with-a-standard-deviation-of-6-feet.-how-many-measurements-should-sahc-plan-to-take-if-it-wants-to-construct-a-0.99-level-confidence-interval-for-ux3bc-that-has-a-length-of-2-feet}{%
\paragraph{Question 4. Mt. Wrightson, the fifth highest summit in
Arizona and the highest in Pima County, has a reputed elevation of 9453
feet. To amuse its members, the Southern Arizona Hiking Club (SAHC)
decides to construct its own confidence interval for μ, the true
elevation of Mt. Wrightson's summit. SAHC acquires an altimeter whose
measurements will have an expected value of μ with a standard deviation
of 6 feet. How many measurements should SAHC plan to take if it wants to
construct a 0.99-level confidence interval for μ that has a length of 2
feet?}\label{question-4.-mt.-wrightson-the-fifth-highest-summit-in-arizona-and-the-highest-in-pima-county-has-a-reputed-elevation-of-9453-feet.-to-amuse-its-members-the-southern-arizona-hiking-club-sahc-decides-to-construct-its-own-confidence-interval-for-ux3bc-the-true-elevation-of-mt.-wrightsons-summit.-sahc-acquires-an-altimeter-whose-measurements-will-have-an-expected-value-of-ux3bc-with-a-standard-deviation-of-6-feet.-how-many-measurements-should-sahc-plan-to-take-if-it-wants-to-construct-a-0.99-level-confidence-interval-for-ux3bc-that-has-a-length-of-2-feet}}

\hypertarget{answer-1}{%
\subsubsection{Answer:}\label{answer-1}}

We know that n is given by (2qSD/L) \^{}2 - \{Trosset page 226\}

Given : standard deviation= 6

The desired interval length is given by 2 feet. The corresponding q
value for 99\% interval is given by

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.995}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.575829
\end{verbatim}

Therefore, plugging in the values we get:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{=}\NormalTok{ (}\DecValTok{2}\SpecialCharTok{*} \FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.995}\NormalTok{) }\SpecialCharTok{*} \DecValTok{6} \SpecialCharTok{/}\DecValTok{2}\NormalTok{)}\SpecialCharTok{\^{}}\DecValTok{2}
\NormalTok{n}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 238.8563
\end{verbatim}

Hence, approximately 239 measurements are required if SAHC plan to
construct a 0.99-level confidence interval for μ that has a length of 2
feet.

\hypertarget{question-1e-code}{%
\subparagraph{Question 1e Code:}\label{question-1e-code}}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1}\SpecialCharTok{{-}}\FunctionTok{pnorm}\NormalTok{(}\FloatTok{0.5}\NormalTok{,}\DecValTok{0}\NormalTok{,}\FloatTok{0.4025}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1070747
\end{verbatim}

\end{document}
